{xCoordinate=517, yCoordinate=799, cityIndex=1};
{xCoordinate=643, yCoordinate=596, cityIndex=2};
{xCoordinate=270, yCoordinate=169, cityIndex=3};
{xCoordinate=202, yCoordinate=171, cityIndex=4};
{xCoordinate=798, yCoordinate=458, cityIndex=5};
{xCoordinate=172, yCoordinate=798, cityIndex=6};
{xCoordinate=557, yCoordinate=792, cityIndex=7};
{xCoordinate=295, yCoordinate=768, cityIndex=8};
{xCoordinate=516, yCoordinate=393, cityIndex=9};
{xCoordinate=448, yCoordinate=505, cityIndex=10};
{xCoordinate=744, yCoordinate=672, cityIndex=11};
{xCoordinate=581, yCoordinate=179, cityIndex=12};
{xCoordinate=496, yCoordinate=160, cityIndex=13};
{xCoordinate=362, yCoordinate=733, cityIndex=14};
{xCoordinate=385, yCoordinate=247, cityIndex=15};
RestrictionsArray=0,15,6,7,14,14,14,10,9,5,5,11,15,11,13